export const SET_KRAKEN_PAIRS = 'setKrakenPairs'
export const SET_BITFINEX_PAIRS = 'setBitfinexPairs'
export const SET_BINANCE_PAIRS = 'setBinancePairs'
export const SET_HITBTC_PAIRS = 'setHitbtcPairs'
export const SET_OKEX_PAIRS = 'setOkexPairs'

export const SET_KRAKEN_ERROR = 'setKrakenError'
export const SET_BITFINEX_ERROR = 'setBitfinexError'
export const SET_BINANCE_ERROR = 'setBinanceError'
export const SET_HITBTC_ERROR = 'setHitbtcError'
export const SET_OKEX_ERROR = 'setOkexError'