export const SET_KRAKEN_PAIRS = 'setKrakenPairs'
export const SET_BITFINEX_PAIRS = 'setBitfinexPairs'
export const SET_BINANCE_PAIRS = 'setBinancePairs'
export const SET_HITBTC_PAIRS = 'setHitbtcPairs'
export const SET_OKEX_PAIRS = 'setOkexPairs'